### ISSUE TITLE
Defining scanValue directly as a stack

### ISSUE THREAD

**Issue by joaopaulo-cerquinhocajueiro** [wditch/plcLib#1]
I think that this would simplify the code and it would be much better to use the stack.

**Comment by wditch** [comment]
Version 1.0 did introduce an optional 32 level single-bit stack feature which may be used to solve complex logic circuits (using block logic 'andBlock' and 'orBlock' commands) in addition to pushing and popping values from the stack. You can create multiple stacks if required. See the Examples/Stack folder and also the
[Stack-based Storage and Logic](http://www.electronics-micros.com/software-hardware/plclib-arduino-stack-based-storage-and-logic/) page of the user manual.
