### ISSUE TITLE
Proposal: using typedef in variables used for rung state

### ISSUE THREAD

**Issue by jm-andonegi** [wditch/plcLib#10]
Hi:
I'm a teacher and I'm using plclib without problem. Thanks to this library, I can work with my students using Arduino compatible industrial boards like Controllino.

I just would like to do a proposal: I found a bit confusing how to declare variables to store temporary rung states. For instance, when you call out() function...
- ... if the argument is an int, the function sends the value to an output number.
- ... if the argument is an unsigned int, the function stores the value in the variable. 

Wouldn't it be clearer to use typedef? Maybe it would be enough to have a typedef for connection numbers an another one for rung states. This is a very simple example: https://create.arduino.cc/editor/automatak/a60ddfa9-c652-45c8-8468-830b440db733/preview

Regards!

**Comment by wditch** [comment]
That is a good idea.

The library does already make limited use of the typdef feature internally, however this could be expanded. For example, you could create a couple of typdefs as aliases for pin names and variables, hence making user code more self explanatory. For example:

  typedef int Pin;
  typedef unsigned int Variable;

  Pin R = A0, S = 3;
  Variable V1, V2;

Hence R and S are pin numbers and V1 and V2 are variables.

You could add that sort of code to any of your sketches immediately.

I will also investigate whether this could be added as standard to a future version of the library.

Regards,
Walter Ditch

**Comment by jm-andonegi** [comment]
Great!

Just one doubt. May be using common names could cause conflicts with other libraries. Do you think it would be better a name like plcPin and plcVariable?
