### ISSUE TITLE
Define I/O pins for ESPRESSIF ESP32-DEVKITC

### ISSUE THREAD

**Issue by pawisoon** [wditch/plcLib#13]
Hi,
I got one of the boards from TME and I'm trying to define the IO pins to work with this library.
Can you add support for this [board](https://www.tme.eu/en/details/esp32-devkitc/development-kits-others/espressif/) ? 

[Datasheet](https://www.tme.eu/en/Document/31b16b9b46c633740aeab1a29cd0f7fd/esp32-devkit.pdf)

From ESP32  arduino library I know that:
```
#ifndef Pins_Arduino_h
#define Pins_Arduino_h

#include <stdint.h>

#define EXTERNAL_NUM_INTERRUPTS 16
#define NUM_DIGITAL_PINS        40
#define NUM_ANALOG_INPUTS       16

#define analogInputToDigitalPin(p)  (((p)<20)?(esp32_adc2gpio[(p)]):-1)
#define digitalPinToInterrupt(p)    (((p)<40)?(p):-1)
#define digitalPinHasPWM(p)         (p < 34)

static const uint8_t LED_BUILTIN = 2;
#define BUILTIN_LED  LED_BUILTIN // backward compatibility

static const uint8_t TX = 1;
static const uint8_t RX = 3;

static const uint8_t SDA = 21;
static const uint8_t SCL = 22;

static const uint8_t SS    = 5;
static const uint8_t MOSI  = 23;
static const uint8_t MISO  = 19;
static const uint8_t SCK   = 18;

static const uint8_t A0 = 36;
static const uint8_t A3 = 39;
static const uint8_t A4 = 32;
static const uint8_t A5 = 33;
static const uint8_t A6 = 34;
static const uint8_t A7 = 35;
static const uint8_t A10 = 4;
static const uint8_t A11 = 0;
static const uint8_t A12 = 2;
static const uint8_t A13 = 15;
static const uint8_t A14 = 13;
static const uint8_t A15 = 12;
static const uint8_t A16 = 14;
static const uint8_t A17 = 27;
static const uint8_t A18 = 25;
static const uint8_t A19 = 26;

static const uint8_t T0 = 4;
static const uint8_t T1 = 0;
static const uint8_t T2 = 2;
static const uint8_t T3 = 15;
static const uint8_t T4 = 13;
static const uint8_t T5 = 12;
static const uint8_t T6 = 14;
static const uint8_t T7 = 27;
static const uint8_t T8 = 33;
static const uint8_t T9 = 32;

static const uint8_t DAC1 = 25;
static const uint8_t DAC2 = 26;

#endif /* Pins_Arduino_h */

```
Cheers,
Pawel

**Comment by wditch** [comment]
Hi Pawel

I'm currently on holiday but will have a look at it on my return. Does it use the Arduino IDE? Is it programmed in C?

Regards,
Walter

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pawisoon** [comment]
@wditch Yes it uses Arduino IDE and its programmed in C :)

**Comment by wditch** [comment]
Hi Pawel

Good to know it can use the Arduino IDE.

There is no guarantee the library will work – it depends on how compatible it is with an Arduino Uno on which the library is based. However, the only way to find out is to test it.

As a first step you would need to develop a ‘custom IO allocation’. This is discussed in Chapter 23 of the user manual. Begin by picking the IO pins you intend to use for inputs and outputs (unused pins from your list above) and decide on the pin names they will be referred to (from within your sketches), then follow the same procedure as the example given in Section 23.2.

Once you get this working (compiling without errors), begin by testing a basic Blink application, then try some of the other examples supplied with the library.

I have ordered one these boards, so I will also try it out when I get some spare time.

Best wishes,
Walter

**Comment by wditch** [comment]
Hi Pawel

Unfortunately the library is not compatible with the ESPRESSIF Arduino implementation as things stand. I tried the following sketch which attempts to input from the switch and output to the LED. This gives several errors, one of which refers to the AnalogWrite function which is not yet supported by the above implementation. There were other errors too.

Regards,
Walter

// Test Sketch
#define noPinDefs
#include <plcLib.h>

int X0=0, Y0=2;     // Create X0 and Y0 as local pins

void setup() {
  pinMode(X0, INPUT);
  pinMode(Y0, OUTPUT);
}

void loop() {
  in(X0);                  // Read pin 0
  out(Y0);                 // Output to pin 2
}

**Comment by pawisoon** [comment]
Will there be any chance in the near future to start working on support for that board?
