### ISSUE TITLE
Support request for Particle board

### ISSUE THREAD

**Issue by pawisoon** [wditch/plcLib#14]
Hi! 
Is there any chance to get the library support for Particle.io Electron board?
I tried to compile it and it seems to complain only about 3 methods: 
<img width="667" alt="Screenshot 2019-05-13 at 14 17 04" src="https://user-images.githubusercontent.com/6951295/57620785-1a60d100-758a-11e9-9b96-18a434c5bbe8.png">
<img width="639" alt="Screenshot 2019-05-13 at 14 17 25" src="https://user-images.githubusercontent.com/6951295/57620786-1a60d100-758a-11e9-82eb-5a24901416de.png">

Cheers,
Paweł

**Comment by pawisoon** [comment]
I managed to get set, reset methods by changing the 
`if (scanValue == 1)` to `if (scanValue == 0)`
I also renamed `reset` method to `plc_reset`

**Comment by wditch** [comment]
Hi Pawel

I don't have a Particle.io Electron unfortunately so can't comment.

As a general principle I don't think adding support for individual boards is the way to go. For example Platformio.org lists 641 different boards at the moment. If I do develop a new version, I'm more inclined to develop it for a framework (and hence for all devices supporting that framework). I'd also need to rewrite the library from the ground up to do that. That would include redefining the Arduino data types used, to make them portable across systems.

Regarding applications with a strong IoT focus, saving power is key for devices which are battery powered. For example a battery powered device may go into sleep mode for a period of time or until an alarm state is recognised, hence saving power. Plclib doesn't support that mode of operation, so might not be ideal for an IoT application.

Cheers,
Walter
