### ISSUE TITLE
Error when importing library from tutorial

### ISSUE THREAD

**Issue by jm-andonegi** [wditch/plcLib#8]
I got an error message when importing plcLib.zip library to the online Arduino web editor. The file was downloaded [from the tutorial](http://www.electronics-micros.com/software-hardware/plclib-arduino-install/). This file works fine in the Arduino IDE.

But the file [downloaded from Github](https://github.com/wditch/plcLib/blob/master/plcLib.zip) works fine in the Online web editor. The link in the tutorial could be updated so that it points to the library in github

**Comment by jm-andonegi** [comment]
I have tried to compile in the online editor and I have got this error:

/tmp/167876144/libraries/plcLib/plcLib.cpp.o (symbol from plugin): In function `appName':

(.text+0x0): multiple definition of `setupPLC()'

/tmp/167876144/sketch/Prueba_PLC.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2: error: ld returned 1 exit status

exit status 1

**Comment by wditch** [comment]
Files downloaded from gitHub are compatible with the online editor (Versions 1.3 and 1.4). The plcLib project will be hosted officially through gitHub in the future, and all user documentation will be available from the same source.
